[package]
name = "rusty-scheme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-as-inner = "0.5.0"
expect-test = "1.4.0"
logos = "0.12.1"
thiserror = "1.0.31"
